# 📊 WakaTime GitHub Stats Workflow
# This workflow automatically updates your README with WakaTime coding statistics

name: WakaTime Stats

# Controls when the workflow will run
on:
  # Runs automatically every day at midnight UTC
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight
  
  # Allows manual execution
  workflow_dispatch:
  
  # Runs when you push to main
  push:
    branches: [ main ]

# Permissions needed
permissions:
  contents: write

jobs:
  update-readme:
    name: 📈 Update WakaTime Stats
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the repository
      - name: 📥 Checkout repository
        uses: actions/checkout@v4
        
      # Update README with WakaTime stats
      - name: 📊 Update WakaTime Stats
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
          # Customization options
          SHOW_LINES_OF_CODE: "True"
          SHOW_PROFILE_VIEWS: "True"
          SHOW_COMMIT: "True"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_LANGUAGE: "True"
          SHOW_OS: "True"
          SHOW_PROJECTS: "True"
          SHOW_TIMEZONE: "True"
          SHOW_EDITORS: "True"
          SHOW_LANGUAGE_PER_REPO: "True"
          SHOW_SHORT_INFO: "True"
          SHOW_LOC_CHART: "True"
          
          # Locale settings
          LOCALE: "es"  # Spanish locale
          
          # Commit message
          COMMIT_MESSAGE: "📊 Updated WakaTime stats"
          
          # Show updated time
          SHOW_UPDATED_DATE: "True"
          
          # Repository settings
          REPOSITORY: "AntaresAnton/AntaresAnton"